---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-app-externalsecret
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: nextcloud-app-secret
  data:
    - secretKey: NEXTCLOUD_DATABASE_PASSWORD
      remoteRef:
        key: nextcloud/db
        property: password
    - secretKey: NEXTCLOUD_FULLTEXTSEARCH_PASSWORD
      remoteRef:
        key: nextcloud/fulltext-search
        property: password
    - secretKey: NEXTCLOUD_IMAGINARY_SECRET
      remoteRef:
        key: nextcloud/imaginary
        property: secret
    - secretKey: NEXTCLOUD_ADMIN_PASSWORD
      remoteRef:
        key: nextcloud/admin
        property: password
    - secretKey: NEXTCLOUD_RECORDING_SECRET
      remoteRef:
        key: nextcloud/recording
        property: secret
    - secretKey: NEXTCLOUD_REDIS_PASSWORD
      remoteRef:
        key: nextcloud/redis
        property: password
    - secretKey: NEXTCLOUD_SIGNALING_SECRET
      remoteRef:
        key: nextcloud/signaling
        property: secret
    - secretKey: NEXTCLOUD_TALK_SECRET
      remoteRef:
        key: nextcloud/talk
        property: secret
    - secretKey: NEXTCLOUD_TURN_SECRET
      remoteRef:
        key: nextcloud/turn
        property: secret
    - secretKey: NEXTCLOUD_WHITEBOARD_SECRET
      remoteRef:
        key: nextcloud/whiteboard
        property: secret
    - secretKey: NEXTCLOUD_SMTP_USER
      remoteRef:
        key: nextcloud/smtp
        property: user
    - secretKey: NEXTCLOUD_SMTP_PASSWORD
      remoteRef:
        key: nextcloud/smtp
        property: password
