[workspace]
authors = ["Olaf Lipinski <5785856+olipinski@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "rdx-cluster"
platforms = ["osx-arm64"]
version = "0.0.1"

[tasks]

[dependencies]
pre-commit = ">=4.5.1,<5"
pixi-pycharm = ">=0.0.10,<0.0.11"
