---
# This play is for loading required kernel modules
# Longhorn requires dm_crypt module to be loaded
# https://longhorn.io/docs/latest/deploy/install/#installing-cryptsetup-and-luks
- name: Load Longhorn kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  with_items:
    - dm_crypt # General Longhorn
    - nvme-tcp # V2 Engine
    - vfio_pci # V2 Engine
    - uio_pci_generic # V2 Engine
