---
# service node variables

# ###########################
# restic backup role variables
# ###########################
restic_clean_service: true

############################
# OpenBao role variables
############################
openbao_venv_path: /opt/openbao-venv

# ###############################
# Node-exporter Agent configuration
################################
node_exporter_arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"
