---
# service node variables

# ###########################
# restic backup role variables
# ###########################
restic_clean_service: true

############################
# vault role variables
############################
vault_venv_path: /opt/vault-venv

# ###############################
# Node-exporter Agent configuration
################################

node_exporter_arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"
