---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/cert-manager/app/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-webhook-ovh
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-app
    - name: external-secrets-config
  path: ./kubernetes/platform/cert-manager/webhook-ovh/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-app
    - name: cert-manager-webhook-ovh
    - name: external-secrets-config
  path: ./kubernetes/platform/cert-manager/config/overlays/prod
  prune: true
  wait: true
  healthCheckExprs:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      failed: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings