---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-db
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cloudnative-pg-app
    - name: keycloak-operator
  path: ./kubernetes/platform/keycloak/db/overlays/prod
  prune: true
  wait: true
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-operator
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/keycloak/operator/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-app
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: keycloak-db
    - name: keycloak-operator
  path: ./kubernetes/platform/keycloak/app/overlays/prod
  prune: true
  wait: true
  healthCheckExprs:
    - apiVersion: k8s.keycloak.org/v2alpha1
      kind: Keycloak
      failed: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings


---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-config
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: keycloak-app
  path: ./kubernetes/platform/keycloak/config/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings
