---
apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: nextcloud-tcp-route
  labels:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud
spec:
  parentRefs:
    - name: kube-gateway
      sectionName: sub-tcp
  rules:
    - backendRefs:
        - name: docker-mailserver
          port: 10587
