---
# velero helm values (base)

# AWS backend and CSI plugins configuration
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.2@sha256:0751144c1c8e52d52c48717fbd13ad5a3061e612ae4d7ad744a946cd5b139d1a
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

# Velero Configuration
configuration:
  # Configure SeaweedFS S3 as backup backend
  backupStorageLocation:
    - provider: aws
      bucket: k3s-velero
      config:
        region: eu-east-0
        s3ForcePathStyle: true
        s3Url: https://${S3_SERVER}:8443
  # Enable CSI snapshot support
  features: EnableCSI
credentials:
  existingSecret: velero-s3-secret

# Disable VolumeSnapshotLocation CRD. It is not needed for CSI integration
snapshotsEnabled: false
