---
# velero helm values (base)

# AWS backend and CSI plugins configuration
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.1@sha256:1493a0039cd5cb31004cfbb52f8a1990bc0ed81497ce72516bc76fa9e21506c1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

# Velero Configuration
configuration:
  # Configure Minio as backup backend
  backupStorageLocation:
    - provider: aws
      bucket: k3s-velero
      config:
        region: eu-west-1
        s3ForcePathStyle: true
        s3Url: https://${S3_BACKUP_SERVER}:9091
  # Enable CSI snapshot support
  features: EnableCSI
credentials:
  existingSecret: velero-secret

# Disable VolumeSnapshotLocation CRD. It is not needed for CSI integration
snapshotsEnabled: false

# Override kubectl image to avoid bitnami dependency
# This should be updated when velero has a final solution to depending on bitnami images
# https://github.com/vmware-tanzu/helm-charts/issues/698
kubectl:
  image:
    repository: docker.io/bitnamilegacy/kubectl
    tag: 1.33.4@sha256:ed0b31a0508da84ee655c5c6e01bd3897fc56ad6cf69debb27fa1893a06d2246
