---
# velero helm values (base)

# AWS backend and CSI plugins configuration
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.1@sha256:1493a0039cd5cb31004cfbb52f8a1990bc0ed81497ce72516bc76fa9e21506c1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

# Velero Configuration
configuration:
  # Configure SeaweedFS S3 as backup backend
  backupStorageLocation:
    - provider: aws
      bucket: k3s-velero
      config:
        region: eu-east-0
        s3ForcePathStyle: true
        s3Url: https://${S3_SERVER}:8443
  # Enable CSI snapshot support
  features: EnableCSI
credentials:
  existingSecret: velero-s3-secret

# Disable VolumeSnapshotLocation CRD. It is not needed for CSI integration
snapshotsEnabled: false
