---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-s3-externalsecret
  namespace: velero
spec:
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: velero-s3-secret
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id: "{{ .user | toString }}"
          aws_secret_access_key: "{{ .key | toString }}"
  data:
    - secretKey: user
      remoteRef:
        key: seaweedfs/velero
        property: user
    - secretKey: key
      remoteRef:
        key: seaweedfs/velero
        property: key
