---
- name: Wait for server nodes to be ready # noqa: no-changed-when
  ansible.builtin.command:
    cmd: "kubectl get nodes {{ item }}"
  register: k3s_server_nodes
  until:
    - '" Ready " in k3s_server_nodes.stdout'
  retries: 10
  delay: 5
  with_items: "{{ inventory_hostname }}"
