---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  # Enable plan deployment on server node (noSchedulable by installation)
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  serviceAccountName: system-upgrade
  concurrency: 1
  # Cordon node before upgrading it
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade@sha256:8448c66782e42c7dd562408f5494f2a83ba4086d261dfba2555317d087ce994b
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: v1.35.4+k3s1
