---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  serviceAccountName: system-upgrade
  # Wait for k3s-server upgrade plan to complete before executing k3s-agent plan
  prepare:
    image: rancher/k3s-upgrade:v1.36.3-k3s1@sha256:50f09bc05b24c1911cd5cc6c9d8080c57123cfabcf5f48c1f1ed0e4e022efe25
    args:
      - prepare
      - k3s-server
  concurrency: 1
  # Cordon node before upgrade it
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade:v1.36.3-k3s1@sha256:50f09bc05b24c1911cd5cc6c9d8080c57123cfabcf5f48c1f1ed0e4e022efe25
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: v1.36.2+k3s1
