---
# Pi Cluster variables

# ######
# K3S  #
# ######

# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_release_version: v1.36.2+k3s1

k3s_registration_address: "k8s-api.{{ vault.general.domains.dns }}"
k3s_become: true

# for system-upgrade-controller compatibility
k3s_install_hard_links: true

# k3s server-config
k3s_server:
  # Disable Flannel CNI
  flannel-backend: 'none'
  disable-network-policy: true
  # Disable Helm Controller
  disable-helm-controller: true
  # Disable kube-proxy (using cilium kube-proxy replacement)
  disable-kube-proxy: true
  # Enabling Embedded Registry Mirror (Spegel)
  embedded-registry: true
  # TLS config
  tls-san:
    - "{{ k3s_registration_address }}" # IP to kube-vip
  # Disable K3s addons: coredns, local path, servicelb, traefik and metric-server
  disable:
    - coredns
    - local-storage
    - servicelb
    - traefik
    - metrics-server
  write-kubeconfig-mode: '0644'
  node-taint:
    - node-role.kubernetes.io/control-plane:NoSchedule
  etcd-expose-metrics: true
  kube-controller-manager-arg:
    - terminated-pod-gc-threshold=10

# k3s agent-config
k3s_agent:
  node-label:
    - node_type=agent

# #######################
# K3s install manifests #
# #######################

# These are the manifests needed to get k3s off the ground
# and able to run FluxCD.

install_manifests_dir: "/tmp/k3s-manifests-install"

install_manifests: []

install_charts:
  prometheus-crds:
    chart_ref: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
    version: 30.0.0
    namespace: kube-system
    create_namespace: true
    value_files: []

  cilium:
    chart_ref: oci://quay.io/cilium/charts/cilium
    version: 1.19.5
    namespace: kube-system
    value_files:
      - ../../../../kubernetes/platform/cilium/app/base/values.yaml
      - ../../../../kubernetes/platform/cilium/app/components/istio-config/values.yaml
      - "../../../../kubernetes/platform/cilium/app/overlays/{{ overlay }}/values.yaml"

  coredns:
    chart_ref: oci://ghcr.io/coredns/charts/coredns
    version: 1.46.20
    namespace: kube-system
    value_files:
      - ../../../../kubernetes/platform/coredns/app/base/values.yaml
      - "../../../../kubernetes/platform/coredns/app/overlays/{{ overlay }}/values.yaml"

  kube-vip:
    chart_ref: kube-vip
    repo_url: https://kube-vip.github.io/helm-charts
    version: 0.9.9
    namespace: kube-system
    value_files:
      - "../../../../kubernetes/platform/kube-vip/base/values.yaml"
      - "../../../../kubernetes/platform/kube-vip/overlays/{{ overlay }}/values.yaml"

# #########
# FluxCD #
# #########
# renovate: datasource=github-releases depName=fluxcd/flux2
fluxcd_version: v2.8.6

###########
# Ingress #
###########

# HTTP Basic auth credentials
ingress_basic_auth_user: "{{ vault.ingress.admin.user }}"
ingress_basic_auth_passwd: "{{ vault.ingress.admin.password }}"

# DNS cluster service end-points
traefik_dashboard_dns: "traefik.{{ dns_domain }}"
longhorn_dashboard_dns: "storage.{{ dns_domain }}"
kibana_dashboard_dns: "kibana.{{ dns_domain }}"
elasticsearch_dns: "elasticsearch.{{ dns_domain }}"
fluentd_dns: "fluentd.{{ dns_domain }}"
monitoring_dns: "monitoring.{{ dns_domain }}"
linkerd_dashboard_dns: "linkerd.{{ dns_domain }}"

#################################
# TLS Certificates: LetsEncrypt #
#################################

# Enable letsencrypt certificates
enable_letsencrypt: true

# Cloudflare API token
certmanager_cloudflare_token: "{{ vault.certmanager.cloudflare.token }}"

# issuer email
acme_issuer_email: "admin@{{ vault.general.domains.dns }}"

###############################
# Seaweed FS S3 configuration #
###############################

# Seaweed variables for reuse
seaweedfs_hostname: "s3.{{ vault.general.domains.dns }}"
seaweedfs_master_dir: "/naspool/s3/master"
seaweedfs_volume_dir: "/naspool/s3/volume"

# Role config
# renovate: datasource=github-releases depName=seaweedfs/seaweedfs
seaweedfs_version: 4.35
seaweedfs_arch: arm64
seaweedfs_os: linux
seaweedfs_owner: root
seaweedfs_group: root
seaweedfs_config_dir: /etc/seaweedfs
seaweedfs_service_state: started
seaweedfs_command: server
seaweedfs_args:
  # General options
  - -dataCenter=EU_WAW
  - -rack=R0
  - -dir={{ seaweedfs_volume_dir }}
  - -ip=localhost
  - -ip.bind=localhost
  # Filer options
  - -filer
  - -filer.port=8888
  # S3 Options
  - -s3
  - -s3.ip.bind=0.0.0.0
  - -s3.port=8333
  - -s3.port.https=8443
  - -s3.cert.file={{ seaweedfs_config_dir }}/fullchain.pem
  - -s3.key.file={{ seaweedfs_config_dir }}/privkey.pem
  - -s3.iam=false # Disable IAM, we will only use simple auth
  - -s3.port.iceberg=0 # Disable Iceberg
  # Master options
  - -master.port=9333
  - -master.dir={{ seaweedfs_master_dir }}
  - -master.volumeSizeLimitMB=4096
  - -metricsIp=0.0.0.0
  - -metricsPort=9091
  # Volume options
  - -volume
  - -volume.id=main
  - -volume.port=8080
  - -volume.max=0
  - -volume.fileSizeLimitMB=1024
  # SFTP options
  - -sftp=false
  # WebDAV options
  - -webdav=false

seaweedfs_s3_config:
  identities:
    - name: "{{ vault.seaweedfs.root.user }}"
      actions:
        - "Read"
        - "Write"
        - "List"
        - "Tagging"
        - "Admin"
      credentials:
        - accessKey: "{{ vault.seaweedfs.root.user }}"
          secretKey: "{{ vault.seaweedfs.root.key }}"
    - name: "{{ vault.seaweedfs.restic.user }}"
      actions:
        - "Read:restic"
        - "Write:restic"
        - "List:restic"
        - "Tagging:restic"
        - "Admin:restic"
      credentials:
        - accessKey: "{{ vault.seaweedfs.restic.user }}"
          secretKey: "{{ vault.seaweedfs.restic.key }}"
    - name: "{{ vault.seaweedfs.longhorn.user }}"
      actions:
        - "Read:k3s-longhorn"
        - "Write:k3s-longhorn"
        - "List:k3s-longhorn"
        - "Tagging:k3s-longhorn"
        - "Admin:k3s-longhorn"
      credentials:
        - accessKey: "{{ vault.seaweedfs.longhorn.user }}"
          secretKey: "{{ vault.seaweedfs.longhorn.key }}"
    - name: "{{ vault.seaweedfs.velero.user }}"
      actions:
        - "Read:k3s-velero"
        - "Write:k3s-velero"
        - "List:k3s-velero"
        - "Tagging:k3s-velero"
        - "Admin:k3s-velero"
      credentials:
        - accessKey: "{{ vault.seaweedfs.velero.user }}"
          secretKey: "{{ vault.seaweedfs.velero.key }}"
    - name: "{{ vault.seaweedfs.loki.user }}"
      actions:
        - "Read:k3s-loki"
        - "Write:k3s-loki"
        - "List:k3s-loki"
        - "Tagging:k3s-loki"
        - "Admin:k3s-loki"
      credentials:
        - accessKey: "{{ vault.seaweedfs.loki.user }}"
          secretKey: "{{ vault.seaweedfs.loki.key }}"
    - name: "{{ vault.seaweedfs.tempo.user }}"
      actions:
        - "Read:k3s-tempo"
        - "Write:k3s-tempo"
        - "List:k3s-tempo"
        - "Tagging:k3s-tempo"
        - "Admin:k3s-tempo"
      credentials:
        - accessKey: "{{ vault.seaweedfs.tempo.user }}"
          secretKey: "{{ vault.seaweedfs.tempo.key }}"
    - name: "{{ vault.seaweedfs.barman.user }}"
      actions:
        - "Read:k3s-barman"
        - "Write:k3s-barman"
        - "List:k3s-barman"
        - "Tagging:k3s-barman"
        - "Admin:k3s-barman"
      credentials:
        - accessKey: "{{ vault.seaweedfs.barman.user }}"
          secretKey: "{{ vault.seaweedfs.barman.key }}"

########################
# Restic configuration #
########################

# renovate: datasource=github-releases depName=restic/restic
restic_version: 0.18.1

# Restic S3 repository configuration
restic_repository: s3:https://{{ seaweedfs_hostname }}/restic
restic_use_ca_cert: true
restic_environment:
  - name: AWS_ACCESS_KEY_ID
    value: "{{ vault.seaweedfs.restic.user }}"
  - name: AWS_SECRET_ACCESS_KEY
    value: "{{ vault.seaweedfs.restic.key }}"

#########################
# OpenBao configuration #
#########################

openbao_hostname: "bao.{{ dns_domain }}"
# renovate: datasource=github-releases depName=openbao/openbao
openbao_version: 2.5.4

openbao_dns: "{{ openbao_hostname }}"
openbao_enable_tls: true
openbao_init: true
openbao_save_keys_to_file: true
openbao_unseal: true
openbao_unseal_service: true
openbao_enable_telemetry: true

 # Configure KV
openbao_kv_secrets:
  path: secret

 # Policies
policies:
  - name: write
    json: |
      {
        "path":{
          "secret/*":{
            "capabilities":[
              "create",
              "read",
              "update",
              "delete",
              "list",
              "patch"
            ]
          }
        }
      }
  - name: read
    json: |
      {
        "path":{
          "secret/*":{
            "capabilities":[
              "read"
            ]
          }
        }
      }

#########################
# Velero  Configuration #
#########################

# renovate: datasource=github-releases depName=vmware-tanzu/velero
velero_version: v1.18.0

# SeaweedFS user, key and bucket
seaweedfs_velero_user: "{{ vault.seaweedfs.velero.user }}"
seaweedfs_velero_key: "{{ vault.seaweedfs.velero.key }}"

velero_secret_content: |
  [default]
  aws_access_key_id: "{{ seaweedfs_velero_user }}"
  aws_secret_access_key: "{{ seaweedfs_velero_key }}"

##########################
# Longhorn Configuration #
##########################

# renovate: datasource=github-releases depName=longhorn/longhorn
longhorn_version: v1.11.1

# SeaweedFS user, key and bucket
seaweedfs_longhorn_user: "{{ vault.seaweedfs.longhorn.user }}"
seaweedfs_longhorn_key: "{{ vault.seaweedfs.longhorn.key }}"

#######################
# Istio Configuration #
#######################

# renovate: datasource=github-releases depName=istio/istio
istio_version: 1.29.2

###################
# Logging Secrets #
###################

# Fluentd-fluentbit shared key
fluentd_shared_key: "{{ vault.logging.fluentd.shared_key }}"

# Elasticsearch 'elastic' user password
efk_elasticsearch_passwd: "{{ vault.logging.elasticsearch.password }}"

# Loki SeaweedFS user, key and bucket
seaweedfs_loki_user: "{{ vault.seaweedfs.loki.user }}"
seaweedfs_loki_key: "{{ vault.seaweedfs.loki.key }}"

######################
# Monitoring Secrets #
######################

# Grafana admin user password
prometheus_grafana_password: "{{ vault.grafana.admin.password }}"

#######################
# Tracing Secrets     #
#######################

# Tempo SeaweedFS user, key and bucket
seaweedfs_tempo_user: "{{ vault.seaweedfs.tempo.user }}"
seaweedfs_tempo_key: "{{ vault.seaweedfs.tempo.key }}"
seaweedfs_tempo_bucket: k3s-tempo

#######################
# Gateway configuration
#######################
gateway_hostname: "gateway.{{ dns_domain }}"
