---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-externalsecret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-secret
  data:
    - secretKey: CLOUDFLARE_TOKEN
      remoteRef:
        key: certmanager/cloudflare
        property: token
