---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: fluent-operator
  namespace: flux-system
spec:
  url: oci://ghcr.io/fluent/helm-charts/fluent-operator
  interval: 1h
