---
alertmanager:
  route:
    main:
      enabled: true
      hostnames:
        - alertmanager.${CLUSTER_DOMAIN}
      parentRefs:
        - name: kube-gateway
          namespace: envoy-gateway-system

prometheus:
  route:
    main:
      enabled: true
      hostnames:
        - prometheus.${CLUSTER_DOMAIN}
      parentRefs:
        - name: kube-gateway
          namespace: envoy-gateway-system
