---
apiVersion: opentelemetry.io/v1alpha1
kind: ClusterObservability
metadata:
  name: cluster-observability
  namespace: opentelemetry
spec:
  exporter:
    endpoint: "https://opentelemetry-forwarder.${CLUSTER_DOMAIN}:4318"
