apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dms-externalsecret
  namespace: flux-system
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: docker-mailserver-secret
  data:
  - secretKey: dms-admin-user
    remoteRef:
      key: dms/admin
      property: user
  - secretKey: dms-admin-hashed-passowrd
    remoteRef:
      key: dms/admin
      property: hashed_password
  - secretKey: dms-dkim-keys-private
    remoteRef:
      key: dms-dkim/keys
      property: private
  - secretKey: dms-dkim-keys-public
    remoteRef:
      key: dms-dkim/keys
      property: public
  - secretKey: dms-dkim-keys-dns
    remoteRef:
      key: dms-dkim/keys
      property: dns
