apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dms-externalsecret
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: docker-mailserver-secret
  data:
  - secretKey: DMS_ADMIN_USER
    remoteRef:
      key: dms/admin
      property: user
  - secretKey: DMS_ADMIN_HASHED_PASSWORD
    remoteRef:
      key: dms/admin
      property: hashed_password
  - secretKey: DMS_DKIM_KEYS_PRIVATE
    remoteRef:
      key: dms-dkim/keys
      property: private
  - secretKey: DMS_DKIM_KEYS_PUBLIC
    remoteRef:
      key: dms-dkim/keys
      property: public
  - secretKey: DMS_DKIM_KEYS_DNS
    remoteRef:
      key: dms-dkim/keys
      property: dns
