---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm.yaml
  - ingress.yaml

configMapGenerator:
  - name: nextcloud-helm-values
    files:
      - base-values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
