---
- name: Configure rdxcluster nodes backup
  hosts: rdxcluster
  gather_facts: true
  tags:
    - backup
  become: true
  pre_tasks:
    - name: Include vault variables
      ansible.builtin.include_vars: vars/vault.yaml
    - name: Include rdxcluster variables
      ansible.builtin.include_vars: vars/rdxcluster.yaml
    - name: Do not use CA certificate
      ansible.builtin.set_fact:
        restic_use_ca_cert: false
  roles:
    - role: ricsanfre.backup
      tags:
        - backup
