---

- name: Generate vault variables file
  hosts: localhost

  vars_prompt:
    - name: ovh_ak
      prompt: Enter OVH Application Key (AK)
      private: true
    - name: ovh_as
      prompt: Enter OVH Secret Application Key (AS)
      private: true
    - name: ovh_ck
      prompt: Enter OVH Consumer Key (CK)
      private: true
    - name: wifi_password
      prompt: Enter WiFI Password
      private: true
    - name: sec_org
      prompt: Enter organisation name
      private: true
    - name: sec_dns_domain
      prompt: Enter DNS domain
      private: true

  pre_tasks:
    - name: Get GitHub PAT credentials
      when: git_private_repo
      block:
        - name: Ask for GitHub PAT credentials
          ansible.builtin.pause:
            prompt: "Enter Github PAT: "
            echo: false
          register: prompt
        - name: Set GitHub pat password variable
          ansible.builtin.set_fact:
            github_pat: "{{ prompt.user_input }}"
          no_log: true
    - name: Get Telegram credentials
      when: smartmontools_notification_format == "telegram"
      block:
        - name: Ask for Telegram chat ID
          ansible.builtin.pause:
            prompt: "Enter the Telegram chat ID: "
            echo: false
          register: chat_id
        - name: Ask for Telegram bot API key
          ansible.builtin.pause:
            prompt: "Enter the Telegram bot API key: "
            echo: false
          register: bot_key
        - name: Set Telegram chat ID
          ansible.builtin.set_fact:
            telegram_chat_id: "{{ chat_id.user_input }}"
          no_log: true
        - name: Set Telegram boot API key
          ansible.builtin.set_fact:
            telegram_api_key: "{{ bot_key.user_input }}"
          no_log: true
  tasks:
    - name: Create random passwords
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      with_items:
        - k3s_token
        - minio_root_password
        - minio_restic_password
        - minio_longhorn_password
        - minio_velero_password
        - minio_loki_password
        - minio_tempo_password
        - minio_barman_password
        - traefik_basic_auth_password
        - fluentd_shared_key
        - grafana_admin_password
        - elasticsearch_admin_password
        - elasticsearch_fluentd_password
        - elasticsearch_prometheus_password
        - keycloak_admin_password
        - keycloak_pi_password
        - keycloak_postgresql_password
        - oauth2_proxy_client_secret
        - oauth2_proxy_cookie
        - oauth2_proxy_redis_password
        - grafana_client_secret
        - kiali_client_secret
        - postgresql_admin_password

    - name: Generate WireGuard private key
      command: wg genkey
      register: wg_private_key

    - name: Generate vault file
      ansible.builtin.template:
        src: vars/vault.yml.j2
        dest: vars/vault.yml

    - name: Encrypt file
      ansible.builtin.command:
        cmd: ansible-vault encrypt --vault-password-file=./.vault/vault-pass.sh vars/vault.yml
