---
# Deploy Node Exporter to get logs and prometheus metrics
- name: Deploy node exporter agent on external node
  hosts: service0
  gather_facts: true
  become: true
  pre_tasks:
    - name: Include vault variables
      ansible.builtin.include_vars: vars/vault.yaml
      tags:
        - always
    - name: Include rdxcluster variables
      ansible.builtin.include_vars: vars/rdxcluster.yaml
      tags:
        - always
  roles:
    - role: prometheus.prometheus.node_exporter

# Deploy bind exporter to get bind9 metrics
- name: Deploy bind exporter agent on the DNS server
  hosts: gateway0
  gather_facts: true
  become: true
  pre_tasks:
    - name: Include vault variables
      ansible.builtin.include_vars: vars/vault.yaml
      tags:
        - always
    - name: Include rdxcluster variables
      ansible.builtin.include_vars: vars/rdxcluster.yaml
      tags:
        - always
  roles:
    - role: prometheus.prometheus.bind_exporter
