---
- name: Clean SeaweedFS Installation
  hosts: s3
  become: true
  gather_facts: false
  tags:
    - s3
  tasks:
    - name: Stop and disable SeaweedFS Server
      ansible.builtin.systemd:
        name: seaweedfs
        state: stopped
        enabled: false
      become: true
    - name: Delete directories and files
      become: true
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /naspool/s3/volume
        - /naspool/s3/master
        - /etc/seaweedfs
        - /opt/seaweedfs
        - /etc/systemd/system/seaweedfs.service
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

- name: Clean OpenBao Installation
  hosts: bao
  become: true
  gather_facts: false
  tags:
    - openbao
  tasks:
    - name: Stop and disable OpenBao server
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      become: true
      with_items:
        - openbao
        - openbao-unseal
    - name: Delete directories and files
      become: true
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /var/lib/openbao/
        - /etc/openbao/
        - /var/log/openbao/
        - /usr/local/bin/openbao
        - /etc/systemd/system/openbao.service
        - /etc/systemd/system/openbao-unseal.service
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

- name: Clean Restic Installation
  hosts: rdxcluster:gateways
  become: true
  gather_facts: false
  tags:
    - restic
  tasks:
    - name: Stop and disable restic backup service
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      become: true
      with_items:
        - restic-backup.timer

    - name: Stop and disable restic clean service
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      become: true
      when: restic_clean_service
      with_items:
        - restic-clean.timer

    - name: Delete directories and files
      become: true
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /etc/restic/
        - /var/log/restic.log
        - /usr/local/bin/restic
        - /etc/systemd/system/restic-backup.service
        - /etc/systemd/system/restic-backup.timer

    - name: Delete clean service file
      become: true
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /etc/systemd/system/restic-clean.timer
        - /etc/systemd/system/restic-clean.service
      when: restic_clean_service

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
