---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elasticsearch-opentelemetry-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: es-opentelemetry-user-file-realm
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
        roles: opentelemetry_role
  data:
    - secretKey: username
      remoteRef:
        key: elastic/opentelemetry
        property: user
    - secretKey: password
      remoteRef:
        key: elastic/opentelemetry
        property: password
